#!/bin/sh
NEWS=~/news
SVC=heise
URL="https://www.faz.net/rss/aktuell/"
# no user servicable parts below

LOG=$NEWS/log
rm -rf $NEWS/$SVC
mkdir -p $LOG
mkdir -p $NEWS/$SVC
cd ~/piTelex/RSS-feed
./rssFileWriter.py -f -n $SVC:  -p "$NEWS/$SVC/" -u "$URL" > $LOG/news-$SVC.log 2> $LOG/news-$SVC.error.log &

