#!/bin/sh
NEWS=~/news
SVC=SZ-komplett
URL="https://rss.sueddeutsche.de/app/service/rss/alles/index.rss?output=rss"
# no user servicable parts below

LOG=$NEWS/log
rm -rf $NEWS/$SVC
mkdir -p $LOG
mkdir -p $NEWS/$SVC
cd ~/piTelex/RSS-feed
./rssFileWriter.py -f -n $SVC:  -p "$NEWS/$SVC/" -u "$URL" > $LOG/news-$SVC.log 2> $LOG/news-$SVC.error.log &

