#!/bin/sh
cd ~/piTelex
rm -rf /data/piTelex/news/sz-alles
mkdir -p /data/piTelex/news/sz-alles
./rssFileWriter.py -f -n SZ:\  -p /data/piTelex/news/sz-alles/sz-alles -u "https://rss.sueddeutsche.de/app/service/rss/alles/index.rss?output=rss" > /data/piTelex/log/news-sz-alles.log 2> /data/piTelex/log/news-sz-alles.error.log &

